### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by badtrip987** [LimbixHealth/limbix-docker-ffmpeg#1]
Hey,

Tried to install on Windows but it failed.

Could you take a look or point me in the right direction?

Thanks

**Comment by scott-limbix** [comment]
Unfortunately, we don't have a Windows machine to test on, or reproduce the issue.  If you can submit a pull request, we'd be happy to merge your fix!

What is the issue you're seeing?

**Comment by badtrip987** [comment]
For future reference:
Git altered the file to put windows style line endings. To fix the issue, you have to make sure the file is using linux style line endings.
